export const STRINGS = {
    inputFirstNamePH : 'First Name',
    inputLastNamePH : 'Last Name',
    inputPostalCodePH : 'Zip/Postal Code',
    btnContinue : 'CONTINUE',
    btnCancel : 'CANCEL',
    columnQtyTitle : 'QTY',
    columnDescriptionTitle : 'DESCRIPTION',
    errorFirstName : 'First Name is required',
    errorLastName : 'Last Name is required',
    errosPostaCode : 'Postal Code is required',
    paymentInformation : 'Payment Information:',
    shippingInformation : 'Shipping Information:',
    btnFinish : 'FINISH',
    btnCancel : 'CANCEL',
    priceSubtotalTitle : 'Item total: $',
    priceTaxTitle : 'Tax: $',
    priceTotalTitle : 'Total: $',
    pageYourInformationTitle : 'Checkout: Your Information',
    pageOverViewTitle : 'Checkout: Overview'
}